apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: astro-vue-demo-ingress
  namespace: dev-antonio
spec:
  ingressClassName: traefik
  rules:
  - host: demo.dev-antonio.local
    http:
      paths:
      - backend:
          service:
            name: astro-vue-demo
            port:
              number: 80
        path: /
        pathType: Prefix
      - backend:
          service:
            name: springboot-demo
            port:
              number: 8080
        path: /api
        pathType: Prefix