apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: springboot-demo-ingress
  namespace: dev-antonio
spec:
  ingressClassName: traefik
  rules:
  - host: api-demo.dev-antonio.local
    http:
      paths:
      - backend:
          service:
            name: springboot-demo
            port:
              number: 8080
        path: /
        pathType: Prefix
