apiVersion: v1
kind: Service
metadata:
  name: astro-vue-demo
  namespace: dev-antonio
spec:
  clusterIP: 10.43.87.115
  clusterIPs:
  - 10.43.87.115
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: astro-vue-demo-service
    port: {{ .Values.servicePort }}
    protocol: TCP
    targetPort: {{ .Values.servicePort }}
  selector:
    app: astro-vue-demo-frontend
  sessionAffinity: None
  type: ClusterIP
