apiVersion: v1
kind: Service
metadata:
  name: springboot-demo
  namespace: dev-antonio
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: springboot-demo-service
    port: {{ .Values.servicePort }}
    protocol: TCP
    targetPort: {{ .Values.servicePort }}
  selector:
    app: springboot-demo-api
  sessionAffinity: None
  type: ClusterIP
